apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-storage
spec:
  serviceName: svc-storage
  replicas: 1
  selector:
    matchLabels:
      app: backend-storage
  template:
    metadata:
      labels:
        app: backend-storage
    spec:
      containers:
        - name: backend-storage
          image: gcr.io/javierahumadaortiz/backend-storage:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: backend-storage-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: backend-storage-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
